/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vue;

import Model.Hebergement;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PROBOOK 450 I7
 */
public class FrmAcceuil extends javax.swing.JInternalFrame {

    ImageIcon photo;
    Hebergement he = new Hebergement();
    private List<Hebergement> list = new ArrayList<>();
            
    
    
    
    
    /**
     * Creates new form NewJInternalFrame
     */
    public FrmAcceuil() {
        initComponents();
        
        try {
            this.setMaximum(true);
            //this.setExtendedState(MAXIMIZED_BOTH);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmAcceuil.class.getName()).log(Level.SEVERE, null, ex);
        }
        charger();
    }
    
    public void modP(int pos,int x, int y, JLabel lbl, JLabel lblNom,JLabel lblAdresse){
        //list = he.topHebergement();
        String chemin = list.get(pos).getPhoto();
        photo=new ImageIcon(chemin);
        //redimentionnement de l'image en fonction de la zone d'affichage
        photo=new ImageIcon(photo.getImage().getScaledInstance(x,y, Image.SCALE_DEFAULT));
        //affichage de l'image dans la zone 
        lbl.setIcon(photo);
        //affichage du nom dans la zone
        lblNom.setText(list.get(pos).getNom());
        //affichage de l'adresse dans la zone 
        lblAdresse.setText(list.get(pos).getAdresse());
    }
    
    
    public void charger()
    {
        list = he.topHebergement();
        modP(0,485,294,lblPrincipale,lblPrincipaleNom,lblPrincipaleAdresse);
        modP(1, 209, 215, lbl2, lbl2Nom, lbl2Adresse);
        modP(2, 209, 215, lbl3, lbl3Nom, lbl3Adresse);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPrincipale = new javax.swing.JLabel();
        lblPrincipaleNom = new javax.swing.JLabel();
        lblPrincipaleAdresse = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl2Nom = new javax.swing.JLabel();
        lbl2Adresse = new javax.swing.JLabel();
        lbl3Adresse = new javax.swing.JLabel();
        lbl3Nom = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPrincipale.setBackground(new java.awt.Color(102, 102, 102));
        lblPrincipale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPrincipale.setMaximumSize(new java.awt.Dimension(191, 221));
        lblPrincipale.setMinimumSize(new java.awt.Dimension(191, 221));
        lblPrincipale.setPreferredSize(new java.awt.Dimension(191, 221));

        lblPrincipaleNom.setBackground(new java.awt.Color(255, 255, 255));
        lblPrincipaleNom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPrincipaleNom.setText("Bonjour");

        lblPrincipaleAdresse.setBackground(new java.awt.Color(255, 255, 255));
        lblPrincipaleAdresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPrincipaleAdresse.setText("13 Rue dodo");

        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl2Nom.setBackground(new java.awt.Color(255, 255, 255));
        lbl2Nom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl2Nom.setText("Bonjour");

        lbl2Adresse.setBackground(new java.awt.Color(255, 255, 255));
        lbl2Adresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl2Adresse.setText("13 Rue dodo");

        lbl3Adresse.setBackground(new java.awt.Color(255, 255, 255));
        lbl3Adresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl3Adresse.setText("13 Rue dodo");

        lbl3Nom.setBackground(new java.awt.Color(255, 255, 255));
        lbl3Nom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl3Nom.setText("Bonjour");

        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                        .addComponent(lblPrincipaleNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrincipaleAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl2Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl2Adresse, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl3Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrincipaleNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrincipaleAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3Adresse)
                    .addComponent(lbl2Adresse)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl2Adresse;
    private javax.swing.JLabel lbl2Nom;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3Adresse;
    private javax.swing.JLabel lbl3Nom;
    private javax.swing.JLabel lblPrincipale;
    private javax.swing.JLabel lblPrincipaleAdresse;
    private javax.swing.JLabel lblPrincipaleNom;
    // End of variables declaration//GEN-END:variables
}
