/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vue;

import Model.Client;
import Model.Employe;
import Model.Hebergement;
import Model.UserManager;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author PROBOOK 450 I7
 */
public class FrmAcceuil extends javax.swing.JInternalFrame {

    ImageIcon photo;
    Hebergement he = new Hebergement();
    Client cl = new Client();
    Employe em = new Employe();
    private List<Hebergement> list = new ArrayList<>();
            
    
    
    
    
    /**
     * Creates new form NewJInternalFrame
     */
    public FrmAcceuil() {
        initComponents();
        
        try {
            this.setMaximum(true);
            //this.setExtendedState(MAXIMIZED_BOTH);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmAcceuil.class.getName()).log(Level.SEVERE, null, ex);
        }
        charger();
        /*if (UserManager.getVerif() == 0) {
            Charger1();
        }*/
    }
    
    public void modP(int pos,int x, int y, JLabel lbl, JLabel lblNom,JLabel lblAdresse,JLabel lblId){
        //list = he.topHebergement();
        String chemin = list.get(pos).getPhoto();
        photo=new ImageIcon(chemin);
        //redimentionnement de l'image en fonction de la zone d'affichage
        photo=new ImageIcon(photo.getImage().getScaledInstance(x,y, Image.SCALE_DEFAULT));
        //affichage de l'image dans la zone 
        lbl.setIcon(photo);
        //affichage du nom dans la zone
        lblNom.setText(list.get(pos).getNom());
        //affichage de l'adresse dans la zone 
        lblAdresse.setText(list.get(pos).getAdresse());
        lblId.setText(Integer.toString(list.get(pos).getId()));
    }
    
    
    public void charger()
    {
        list = he.topHebergement();
        modP(0,485,294,lblPrincipale,lblPrincipaleNom,lblPrincipaleAdresse,lblPricipaleId);
        modP(1, 209, 215, lbl2, lbl2Nom, lbl2Adresse,lbl2Id);
        modP(2, 209, 215, lbl3, lbl3Nom, lbl3Adresse,lbl3Id);
        
    }
    
    public void Charger1(){
        //btnDelete.setVisible(false);
        //btnModif.setVisible(false);
    }
    
    public void profilCl(){
        
        cl = cl.clientActu(UserManager.getEmail(), UserManager.getPassword());
        
        String chemin = cl.getPhoto();
        photo=new ImageIcon(chemin);
        //redimentionnement de l'image en fonction de la zone d'affichage
        photo=new ImageIcon(photo.getImage().getScaledInstance(77,77, Image.SCALE_DEFAULT));
        //affichage de l'image dans la zone 
        lblPhoto.setIcon(photo);
        //affichage du nom dans la zone
        lblNom.setText(cl.getNom());
        
    }
    
    public void profilEm(){
        
        em = em.EmplActu(UserManager.getEmail(), UserManager.getPassword());
        
        /*String chemin = em.getPhoto();
        photo=new ImageIcon(chemin);
        //redimentionnement de l'image en fonction de la zone d'affichage
        photo=new ImageIcon(photo.getImage().getScaledInstance(77,77, Image.SCALE_DEFAULT));
        //affichage de l'image dans la zone 
        lblPhoto.setIcon(photo);*/
        //affichage du nom dans la zone
        lblNom.setText(em.getNom());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPrincipale = new javax.swing.JLabel();
        lblPrincipaleNom = new javax.swing.JLabel();
        lblPrincipaleAdresse = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl2Nom = new javax.swing.JLabel();
        lbl2Adresse = new javax.swing.JLabel();
        lbl3Adresse = new javax.swing.JLabel();
        lbl3Nom = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNom = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblPricipaleId = new javax.swing.JLabel();
        lbl3Id = new javax.swing.JLabel();
        lbl2Id = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPrincipale.setBackground(new java.awt.Color(102, 102, 102));
        lblPrincipale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPrincipale.setMaximumSize(new java.awt.Dimension(191, 221));
        lblPrincipale.setMinimumSize(new java.awt.Dimension(191, 221));
        lblPrincipale.setPreferredSize(new java.awt.Dimension(191, 221));
        lblPrincipale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrincipaleMouseClicked(evt);
            }
        });

        lblPrincipaleNom.setBackground(new java.awt.Color(255, 255, 255));
        lblPrincipaleNom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPrincipaleNom.setText("Bonjour");

        lblPrincipaleAdresse.setBackground(new java.awt.Color(255, 255, 255));
        lblPrincipaleAdresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPrincipaleAdresse.setText("13 Rue dodo");

        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lbl2Nom.setBackground(new java.awt.Color(255, 255, 255));
        lbl2Nom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl2Nom.setText("Bonjour");

        lbl2Adresse.setBackground(new java.awt.Color(255, 255, 255));
        lbl2Adresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl2Adresse.setText("13 Rue dodo");

        lbl3Adresse.setBackground(new java.awt.Color(255, 255, 255));
        lbl3Adresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl3Adresse.setText("13 Rue dodo");

        lbl3Nom.setBackground(new java.awt.Color(255, 255, 255));
        lbl3Nom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbl3Nom.setText("Bonjour");

        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        lblNom.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNom.setText("Nom");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblPricipaleId.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPricipaleId.setText("id");

        lbl3Id.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl3Id.setText("id");

        lbl2Id.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbl2Id.setText("id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl2Id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl3Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl3Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl3Id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                            .addComponent(lblPrincipaleAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrincipaleNom, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lblPricipaleId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblPrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrincipaleNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPricipaleId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrincipaleAdresse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl3Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl2Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl3Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl2Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3Adresse)
                    .addComponent(lbl2Adresse)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrincipaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrincipaleMouseClicked
       
        // Récupérer le JDesktopPane du JFrame parent (FrmPrincipale)
        JDesktopPane desktopPane = (JDesktopPane) SwingUtilities.getAncestorOfClass(JDesktopPane.class, this);

        // Récupérer le JInternalFrame parent (FrmHebergement2)
        JInternalFrame internalFrame = (JInternalFrame) SwingUtilities.getAncestorOfClass(JInternalFrame.class, this);

        FrmView fv = new FrmView(lblPrincipaleNom.getText());
        desktopPane.add(fv);
        fv.setVisible(true);

        // Supprimer l'ancien JInternalFrame (FrmHebergement2)
        internalFrame.dispose();
    }//GEN-LAST:event_lblPrincipaleMouseClicked

    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        // Récupérer le JDesktopPane du JFrame parent (FrmPrincipale)
        JDesktopPane desktopPane = (JDesktopPane) SwingUtilities.getAncestorOfClass(JDesktopPane.class, this);

        // Récupérer le JInternalFrame parent (FrmHebergement2)
        JInternalFrame internalFrame = (JInternalFrame) SwingUtilities.getAncestorOfClass(JInternalFrame.class, this);

        FrmView fv = new FrmView(lbl2Nom.getText());
        desktopPane.add(fv);
        fv.setVisible(true);

        // Supprimer l'ancien JInternalFrame (FrmHebergement2)
        internalFrame.dispose();
    }//GEN-LAST:event_lbl2MouseClicked

    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        // Récupérer le JDesktopPane du JFrame parent (FrmPrincipale)
        JDesktopPane desktopPane = (JDesktopPane) SwingUtilities.getAncestorOfClass(JDesktopPane.class, this);

        // Récupérer le JInternalFrame parent (FrmHebergement2)
        JInternalFrame internalFrame = (JInternalFrame) SwingUtilities.getAncestorOfClass(JInternalFrame.class, this);

        FrmView fv = new FrmView(lbl3Nom.getText());
        desktopPane.add(fv);
        fv.setVisible(true);

        // Supprimer l'ancien JInternalFrame (FrmHebergement2)
        internalFrame.dispose();
    }//GEN-LAST:event_lbl3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl2Adresse;
    private javax.swing.JLabel lbl2Id;
    private javax.swing.JLabel lbl2Nom;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3Adresse;
    private javax.swing.JLabel lbl3Id;
    private javax.swing.JLabel lbl3Nom;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPricipaleId;
    private javax.swing.JLabel lblPrincipale;
    private javax.swing.JLabel lblPrincipaleAdresse;
    private javax.swing.JLabel lblPrincipaleNom;
    // End of variables declaration//GEN-END:variables
}
