/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vue;

import Model.Hebergement;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PROBOOK 450 I7
 */
public class FrmHebergement extends javax.swing.JInternalFrame {
    
    ImageIcon photo;
    
    Hebergement he = new Hebergement();
    List<Hebergement> list = new ArrayList<>();

    /**
     * Creates new form FrmHebergement
     */
    public FrmHebergement() {
        initComponents();
        try {
            this.setMaximum(true);
            //this.setExtendedState(MAXIMIZED_BOTH);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmAcceuil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tSituation = new javax.swing.JComboBox<>();
        tSituation1 = new javax.swing.JComboBox<>();
        txtTarif = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        lblTest = new javax.swing.JLabel();
        lblTestNom = new javax.swing.JLabel();
        lblTestAdresse = new javax.swing.JLabel();
        txtTarif1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(87, 66, 157));

        tSituation.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tSituation.setForeground(new java.awt.Color(163, 96, 230));
        tSituation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tSituation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 66, 157), 4));

        tSituation1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tSituation1.setForeground(new java.awt.Color(163, 96, 230));
        tSituation1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tSituation1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 66, 157), 4));
        tSituation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSituation1ActionPerformed(evt);
            }
        });

        txtTarif.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTarif.setForeground(new java.awt.Color(163, 96, 230));
        txtTarif.setText("jTextField1");
        txtTarif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 66, 157), 4));

        btnRechercher.setBackground(new java.awt.Color(51, 51, 255));
        btnRechercher.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRechercher.setForeground(new java.awt.Color(255, 255, 255));
        btnRechercher.setText("Rechercher");
        btnRechercher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 66, 157), 4));
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        lblTest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTestNom.setBackground(new java.awt.Color(255, 255, 255));
        lblTestNom.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTestNom.setText("Bonjour");

        lblTestAdresse.setBackground(new java.awt.Color(255, 255, 255));
        lblTestAdresse.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTestAdresse.setText("13 Rue dodo");

        txtTarif1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTarif1.setForeground(new java.awt.Color(163, 96, 230));
        txtTarif1.setText("jTextField1");
        txtTarif1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 66, 157), 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(tSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSituation1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarif1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRechercher)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTestNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTestAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTest, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(lblTest, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTestNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTestAdresse)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tSituation1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tSituation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTarif1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void modP(int pos,int x, int y, JLabel lbl, JLabel lblNom,JLabel lblAdresse){
        //list = he.topHebergement();
        String chemin = list.get(pos).getPhoto();
        photo=new ImageIcon(chemin);
        //redimentionnement de l'image en fonction de la zone d'affichage
        photo=new ImageIcon(photo.getImage().getScaledInstance(x,y, Image.SCALE_DEFAULT));
        //affichage de l'image dans la zone 
        lbl.setIcon(photo);
        //affichage du nom dans la zone
        lblNom.setText(list.get(pos).getNom());
        //affichage de l'adresse dans la zone 
        lblAdresse.setText(list.get(pos).getAdresse());
    }
    
    
    
    private void tSituation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSituation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSituation1ActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
        int tarif = Integer.parseInt(txtTarif.getText());
        list = he.rechercherH(tarif);
        
        
        try {
            if (list != null) {
                modP(0,209 ,215 , lblTest, lblTestNom, lblTestAdresse);
            }else{
                JOptionPane.showMessageDialog(this, "Logement introuvable","Message", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            e.getStackTrace();
        }
        
    }//GEN-LAST:event_btnRechercherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRechercher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTestAdresse;
    private javax.swing.JLabel lblTestNom;
    private javax.swing.JComboBox<String> tSituation;
    private javax.swing.JComboBox<String> tSituation1;
    private javax.swing.JTextField txtTarif;
    private javax.swing.JTextField txtTarif1;
    // End of variables declaration//GEN-END:variables
}
